config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get  'welcome/home'
  get  'welcome/about', as: "about"

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get     'login',  to: 'sessions#new'
  post    'login',  to: 'sessions#create'
  delete  'logout', to: 'sessions#destroy'

  resources :categories, except: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :email, presence: true, uniqueness: true, email: true
  validates :name,  presence: true, uniqueness: { case_sensitive: false },
                    length: { minimum: 3, maximum:25 }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article,       only:   [:edit, :update, :show, :destroy]
  before_action :require_user,      expect: [:index, :show]
  before_action :require_same_user, only:   [:edit,:update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Artcile was sucesfull created"
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was succesful update"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end


  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title,:description)
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:danger] = "You can only edit and delete your own article"
        redirect_to root_path
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin)
      flash[:danger] = "Only admin can create categories"
      redirect_to categories_path
    end
  end
end

app/controllers/rubys_controller.rb
class RubysController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have succesfull login in"
      redirect_to users_path(user)
    else
      flash.now[:danger] = "Email or password not correct"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,          only: [:edit, :show, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin,     only: [:destroy]
  def index
    @users = User.paginate(page: params[:page],per_page: 5 )
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to my blog #{@user.name}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Succesfull change #{@user.name} settings"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    flash[:danger] = "User was succesful deleted"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "You can edit only your profile"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "Only admin user can destroy user"
      redirect_to root_path
    end
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url   = "https://www.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "img-circle")
  end
end

app/views/articles/_articles.html.erb
<div align="center">
<%= will_paginate articles %>
</div>
<% articles.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article), class: "text-primer"%>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length:100) %>
        </div>
        <% if logged_in? && current_user == (article.user || current_user.admin?) %>
          <div class="article-actions">
              <%= link_to "Edit article", edit_article_path(article), class: "btn  btn-success btn-xs" %>
              <%= link_to "Delete article", article_path(article), method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-danger btn-xs" %>
          </div>
        <% end %>
        <div class="aritcle-meta-createby">
          <small><%= article.user.name + ', ' if article.user %> (created_at: <%= time_ago_in_words(article.created_at) %> , updated_at: <%= time_ago_in_words(article.updated_at) %> )</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
<div align="center">
<%= will_paginate articles %>
</div>

app/views/articles/edit.html.erb
<h1> Edit article </h1>
<%= render "articles/shared/form_for_article" %><br />
<div class="col-sm-offset-4 col-sm-4">
  <%= link_to "Show article", article_path(@article), class: "center" %>
</div>

app/views/articles/index.html.erb
<h1 class="center"> Listing of all Articles </h1>
<div align="center">
  <%= render 'articles', articles: @articles %>
  <%= link_to "Create new article", new_article_path, method: :get, class: "btn btn-default" %> |
  <%= link_to "Home", root_path, class: "btn btn-default " %>
</div>

app/views/articles/new.html.erb
<%= render "articles/shared/form_for_article" %>

app/views/articles/shared/_form_for_article.html.erb
<h1 class="center">Create new Article </h1>
<%= render 'shared/messages', obj: @article %>
<%= form_for(@article, html: { class: "form-horizontal" }) do |f| %>
  <div class="row">
    <div class="form-group">
      <%= f.label :title, class: "col-sm-2 control-label" %>
      <div class="col-sm-8">
        <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-8">
        <%= f.text_area :description, class: "form-control", rows: 10,placeholder: "Base of the article" %>
      </div>
    </div>
    <div class="col-sm-offset-2 col-sm-8">
      <%= f.submit "Submit", class: "btn btn-primary btn-xlg" %>
    </div>
  </div>
<% end %> <br />
<div class="col-sm-offset-4 col-sm-4">
  [ <%= link_to "Cancel and back to see all articles", articles_path %> ]
</div>
m

app/views/articles/shared/_links.html.erb
<%= link_to "Back to all articles" %>

app/views/articles/show.html.erb
<div class= "center">
  <strong><h2 class="text-uppercase" >title:<span class="bg-info text-uppercase center"><%= @article.title %></span></h2>
  </strong>
  <div class= "well col-sm-offset-2 col-sm-8" >
    <h3 class= "text-uppercase">description:</h3>
    <span class="bg-info  text-left "><%= simple_format(@article.description) %></span>
  </div>
  <% if @article.user %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li class= "article-title">
            <%= link_to @article.user.name, user_path(@article.user) %>
          </li>
          <li><small><%= pluralize(@article.user.articles.count, "article")  if @article.user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <div class="col-sm-offset-2 col-sm-8">
    <div class="article-actions">
      <%= link_to "Back to all articles", articles_path, class: "btn btn-default" %>
      <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to "Edit article", edit_article_path(@article), class: "btn  btn-success" %>
        <%= link_to "Delete article", article_path(@article), method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1 align="center"> Listning All Categories </h1>
<div align="center">
  <%= will_paginate %>
    <% @categories.each do |category| %>
      <div class="row", align="center">
        <div class="col-xs-8 col-xs-offset-2">
          <div class="well well-lg">
            <%= link_to category.name, category_path(category) %>
          </div>
        </div>
      </div>
    <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<%= render 'shared/messages', obj: @category %>
<%= form_for(@category, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <div class="row">
    <div class="form-group">
      <%= f.label :name, class: "col-sm-2 control-label" %>
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Your name", autofocus: true %>
      </div>
    </div>
    <div class="col-sm-offset-2 col-sm-8">
      <%= f.submit  class: "btn btn-primary btn-xlg" %>
    </div>
  </div>
<% end %> <br />
<div class="col-sm-offset-4 col-sm-4">
  [ <%= link_to "Cancel and back to see all articles", categories_path %> ]
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render "layouts/shared/menu" %>
  <%= render "layouts/shared/messages" %>
    <div class= "container-fluid" >
      <%= yield %>
    </div>
  <%= render "layouts/shared/footer" %>
  <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/layouts/shared/_alerts.html.erb
<div class='alert alert-<%="#{name}" %>'>
  <a href="#" class="close" data-dismiss="alert">×</a>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
</div>

app/views/layouts/shared/_footer.html.erb
    <footer class="footer">
      <div class="container-fluid">
        <span class="text-mute">Copyrigth &copy;
        <%= link_to "Synion", "https://szymonlach.herokuapp.com", data: { confirm: "YOU REALE WANT SEE MY FIRST SITE?" } %></span>
        <nav>
          <ul>
            <li><%= link_to "About", about_path, id:"white" %></li>
          </ul>
        </nav>
      </div>
    </footer>

app/views/layouts/shared/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "M-Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li ><%= link_to "Articles", articles_path, class: "btn", id: "menu-articles" %></li>
        <li><%= link_to "All Users", users_path, class: "btn", id: "menu-articles" %></li>
          <% if logged_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" id= "white" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li></li>
              <li><%= link_to "New article", new_article_path,class: "btn", id: "menu-articles-dropdown" %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
          <% end %>
           <li class="dropdown">
          <a href="#" class="dropdown-toggle" id= "white" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li></li>
              <li><%= link_to "All categories" %></li>
              <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>
              <% if logged_in? && current_user.admin %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "New Category", new_category_path %></li>
              <% end %>
            </ul>
          </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile<%= " Admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path%></li>
        <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/shared/_messages.html.erb
<div class="container">
  <% flash.each do |name,msg| %>
    <div class="row">
      <div class= "col-sm-offset-2 col-sm-8">
        <div class="alert alert-<%= name %>" alert-dismissable">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <h4><strong><%= name.upcase %></strong> <small><%= msg %></small></h4>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/shared/_warning.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(flash[name].count, "error") %>
          prohibited this article from being saved:
        </h2>
        <div class="panel-body">
          <ul>
            <li><%= msg %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_messages.html.erb
  <% if obj.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
              prohibited this article from being saved:
            </h2>
            <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/users/edit.html.erb
<h1 class="center"> Edit yourself </h1>
<%= render 'users/shared/form' %>

app/views/users/index.html.erb
<h1 class= "center"> All Bloggers</h1>
<div align="center">
  <%= will_paginate %>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class= "article-title">
            <%= link_to user.name, user_path(user) %>
          </li>
          <li><small><%= pluralize(user.articles.count, "article") %></small></li>
          <% if logged_in? and current_user.admin? %>
            <li><%= link_to "Delete user", user_path(user), method: :delete, data: { confirm: "Confir are you sure whant to delete user"} %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 class="center">Sign up</h1>
<%= render "users/shared/form" %>

app/views/users/shared/_form.html.erb
<%= render 'shared/messages', obj: @user %>
<%= form_for(@user, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <div class="row">
    <div class="form-group">
      <%= f.label :name, class: "col-sm-2 control-label" %>
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Your name", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email, class: "col-sm-2 control-label" %>
      <div class="col-sm-8">
        <%= f.email_field :email, class: "form-control", placeholder: "Your email", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :password, class: "col-sm-2 control-label" %>
      <div class="col-sm-8">
        <%= f.password_field :password, class: "form-control", placeholder: "Password better > 6 digits" %>
      </div>
    </div>
    <div class="col-sm-offset-2 col-sm-8">
      <%= f.submit(@user.new_record? ? "Sign Up" : "Udpate accout" , class: "btn btn-primary btn-xlg") %>
    </div>
  </div>
<% end %> <br />
<div class="col-sm-offset-4 col-sm-4">
  [ <%= link_to "Cancel and back to see all articles", articles_path %> ]
</div>

app/views/users/show.html.erb
<h1 class="center">Welcome to <%= @user.name %>`s page </h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4  center">
    <%= gravatar_for @user%>
  </div>
</div>
<h4 class="center"><%= @user.name %>`s atricles </h4>
<%= render 'articles/articles', articles: @user_articles %>

app/views/welcome/about.html.erb
<h1> Hi my name is Synion </h1>
<nav>
  <ul>
    <%= link_to "Go to home page", welcome_home_path  %> |
    <%= link_to  "Welcome" %>
  </ul>
</nav>

app/views/welcome/home.html.erb
<div class="jumbotron center">
<h1> Welcome to my Site </h1>
<%= link_to "Sign up!", signup_path, class: "btn btn-primary btn-lg btn-xlg", id: "white" %>
</div>